---
- hosts: dev
  become: true
  tasks:
   - name: Install software
     yum:
      name:
       - httpd
       - mysql
       - mysql-server
       - php
       - php-mysqlnd
      state: latest

   - name: Copy new index.html
     template:
      src: templates/index.html.template
      dest: /var/www/html/index.html
     notify:
      - restart mysqld service
      - restart httpd service

  handlers:
   - name: restart mysqld service
     service:
      name:
       mysqld
      state: started

   - name: restart httpd service
     service:
      name:
       httpd
      state: started
...
